apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vdc-cloud-uat-zilliz-cn-autocertmanager
  namespace: istio-system
spec:
  dnsNames:
    - '*.cloud-uat.zilliz.cn'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-ali
  privateKey:
    rotationPolicy: Always
  secretName: vdc-cloud-uat-zilliz-cn-autocertmanager
